FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements/requirements_user.txt .
RUN pip install --no-cache-dir -r requirements_user.txt

COPY Streamlit /app/Streamlit

EXPOSE 8501

CMD ["streamlit", "run", "Streamlit/dash_PyPAH.py", "--server.address=0.0.0.0", "--server.port=8501"]